# Generated by Django 3.2.22 on 2023-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20231026_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Обработан/Не обработан'),
        ),
    ]
